# fly.toml app configuration file generated for podcastai on 2023-09-27T18:22:56-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "podcastai"
primary_region = "yyz"

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
